--create database if not exists orders_db;
--#use orders_db;

create table orders (
    id bigint generated by default as identity primary key,
    sku_code varchar(255) not null,
    price decimal(19,2) not null,
    quantity int not null
);